config/routes.rb
Project5::Application.routes.draw do

  resources :inventories

  resources :products

  resources :order_lines

  resources :orders

  resources :searches

  post "searches/new"

  get "inventories/index1"
  get "searches/_average"

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  attr_accessible :product_id, :product_name, :quantity
  belongs_to :product

  validates_presence_of :product_id,  :quantity
  validates :quantity, :numericality => { :greater_than_or_equal_to => 0}

end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  # GET /inventories
  # GET /inventories.json


  def index
    @inventories = Inventory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventories }
    end
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
    @inventory = Inventory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventory }
    end
  end

  # GET /inventories/new
  # GET /inventories/new.json
  def new
    @inventory = Inventory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventory }
    end
  end

  # GET /inventories/1/edit
  def edit
    @inventory = Inventory.find(params[:id])
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(params[:inventory])

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render json: @inventory, status: :created, location: @inventory }
      else
        format.html { render action: "new" }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inventories/1
  # PUT /inventories/1.json
  def update
    @inventory = Inventory.find(params[:id])

    respond_to do |format|
      if @inventory.update_attributes(params[:inventory])
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.label :product_id %><br>
    <%= f.collection_select :product_id, Product.all, :id, :product_name, :prompt => true %>

  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<h1>Listing inventories</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Product name</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inventories.each do |inventory| %>
  <tr>
    <td><%= inventory.product_id %></td>
    <td><%= inventory.product_name %></td>
    <td><%= inventory.quantity %></td>
    <td><%= link_to 'Show', inventory %></td>
    <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
    <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/index1.html.erb
<% form_tag projects_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>

app/views/inventories/new.html.erb
<h1>New inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @inventory.product_id %>
</p>

<p>
  <b>Product name:</b>
  <%= @inventory.product_name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @inventory.quantity %>
</p>


<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>