config/routes.rb
Project5::Application.routes.draw do

  resources :inventories

  resources :products

  resources :order_lines

  resources :orders

  resources :searches

  post "searches/new"

  get "inventories/index1"
  get "searches/_average"

end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  attr_accessible :order_id, :product_id, :quantity
  belongs_to :order
  belongs_to :product


  validates_presence_of :order_id, :product_id, :quantity
  validates :quantity, :numericality => { :greater_than_or_equal_to => 0}
end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  # GET /order_lines
  # GET /order_lines.json
  def index
    @order_lines = OrderLine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @order_lines }
    end
  end

  # GET /order_lines/1
  # GET /order_lines/1.json
  def show
    @order_line = OrderLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order_line }
    end
  end

  # GET /order_lines/new
  # GET /order_lines/new.json
  def new
    @order_line = OrderLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order_line }
    end
  end

  # GET /order_lines/1/edit
  def edit
    @order_line = OrderLine.find(params[:id])
  end

  # POST /order_lines
  # POST /order_lines.json
  def create
    @order_line = OrderLine.new(params[:order_line])

    respond_to do |format|
      if @order_line.save
        format.html { redirect_to @order_line, notice: 'Order line was successfully created.' }
        format.json { render json: @order_line, status: :created, location: @order_line }
      else
        format.html { render action: "new" }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /order_lines/1
  # PUT /order_lines/1.json
  def update
    @order_line = OrderLine.find(params[:id])

    respond_to do |format|
      if @order_line.update_attributes(params[:order_line])
        format.html { redirect_to @order_line, notice: 'Order line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_lines/1
  # DELETE /order_lines/1.json
  def destroy
    @order_line = OrderLine.find(params[:id])
    @order_line.destroy

    respond_to do |format|
      format.html { redirect_to order_lines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/views/order_lines/_form.html.erb
<%= form_for(@order_line) do |f| %>
  <% if @order_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_line.errors.count, "error") %> prohibited this order_line from being saved:</h2>

      <ul>
      <% @order_line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.collection_select :order_id, Order.all, :id, :order_no, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.collection_select :product_id, Product.all, :id, :product_name, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_lines/edit.html.erb
<h1>Editing order_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_line %> |
<%= link_to 'Back', order_lines_path %>

app/views/order_lines/index.html.erb
<h1>Listing order_lines</h1>

<table>
  <tr>
    <th>Order</th>
    <th>Product</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @order_lines.each do |order_line| %>
  <tr>
    <td><%= order_line.order_id %></td>
    <td><%= order_line.product_id %></td>
    <td><%= order_line.quantity %></td>
    <td><%= link_to 'Show', order_line %></td>
    <td><%= link_to 'Edit', edit_order_line_path(order_line) %></td>
    <td><%= link_to 'Destroy', order_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order line', new_order_line_path %>

app/views/order_lines/new.html.erb
<h1>New order_line</h1>

<%= render 'form' %>

<%= link_to 'Back', order_lines_path %>

app/views/order_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order:</b>
  <%= @order_line.order_id %>
</p>

<p>
  <b>Product:</b>
  <%= @order_line.product_id%>

</p>

<p>
  <b>Quantity:</b>
  <%= @order_line.quantity %>
</p>


<%= link_to 'Edit', edit_order_line_path(@order_line) %> |
<%= link_to 'Back', order_lines_path %>